title: "Konstantinos Christopoulos"
theme: jekyll-theme-slate  # change to other supported themes if you prefer
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
url: "https://KonstantinosC7.github.io"
baseurl: ""  # leave empty for user/organization pages
social_links:
  github: https://github.com/KonstantinosC7
  linkedin: https://www.linkedin.com/in/konstantinos-christopoulos
  email: christopoulok218@gmail.com
